import type { Metadata } from "next";
import { Geist, Geist_Mono, Alexandria } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const alexandria = Alexandria({
  subsets: ["arabic", "latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-alexandria",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default:"CodeVerse",
    template:"CodeVerse | %s"
  },
  description: "Generated by create next app",
  openGraph: {
    title: "CodeVerse",
    description: "Generated by create next app",
    url: "https://team-portfolio-mauve.vercel.app/",
    siteName: "CodeVerse",
    images: [
      {
        url: "https://team-portfolio-mauve.vercel.app/images/projects/p2.jpg", 
        width: 1200,
        height: 630,
        alt: "CodeVerse",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "CodeVerse",
    description: "Generated by create next app",
    images: ["https://team-portfolio-mauve.vercel.app/images/projects/p2.jpg"], 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${alexandria.variable} ${geistMono.variable}`}
      >
        <div>
          <div>
            <Navbar />
          </div>
          {children}
        </div>
        <ToastContainer />
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
